WebApp/Models/Organization.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApp.Models
{
    public class Organization
    {
        public Organization()
        {
            OrganizationToManagers = new List<OrganizationToManager>();
            AuctionProfiles=new List<AuctionProfile>();
        }
        public Guid OrganizationId { get; set; }
        [Display(Name="Название")]
        public string Name { get; set; }

        public Guid? OrganizationProfileId { get; set; }
        public OrganizationProfile OrganizationProfile { get; set; }

        public Guid? OrganizationBankDetailsId { get; set; }
        public OrganizationBankDetails OrganizationBankDetails { get; set; }

        public Guid? OrganizationProvisionRecipientBankDetailsId { get; set; }
        public OrganizationProvisionRecipientBankDetails OrganizationProvisionRecipientBankDetails { get; set; }

        public Guid? StockId { get; set; }
        public Stock Stock { get; set; }

        public List<OrganizationToManager> OrganizationToManagers { get; set; }
        public List<OrganizationToAdmin> Holders { get; set; }
        public List<OrganizationToSignatory> Signatories { get; set; }
        public List<OrganizationToResponsible> Responsibles{ get; set; }
        

        public List<AuctionProfile> AuctionProfiles { get; set; }
      
    }
}

WebApp/ViewModels/Organizations/IndexViewModel.cs
using System.Collections.Generic;
using WebApp.Models;

namespace WebApp.ViewModels.Organizations
{
    public class IndexViewModel
    {
        public IndexViewModel()
        {
            AsAdmin = new List<Organization>();
            AsManager = new List<Organization>();
            AsResponsible = new List<Organization>();
            AsSignatory = new List<Organization>();
        }
        public List<Organization> AsAdmin { get; set; }
        public List<Organization> AsManager { get; set; }
        public List<Organization> AsResponsible { get; set; }
        public List<Organization> AsSignatory { get; set; }
    }
}

WebApp/Controllers/OrganizationAccessController.cs
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;
using System;
using WebApp.ViewModels.OrganizationAccess;
using System.Security.Claims;
using System.Text;
using System.Threading;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using WebApp.Code;
using WebApp.Services;
using WebApp.ViewModels.WaitingUser;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    public class OrganizationAccessController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly IMyLogger _logger; 

     
        public OrganizationAccessController(ApplicationDbContext context, IEmailSender emailSender, IMyLogger logger)
        {
            _context = context;
            _emailSender = emailSender;
            _logger = logger;
        }

        public async Task<IActionResult> Index(Guid? id)
        {
           
            var model = new IndexViewModel();
            var organization = await _context.Organizations.FirstOrDefaultAsync(x => x.OrganizationId == id);
            model.OrganizationName = organization.Name;
            model.OrganizationId = organization.OrganizationId;

            model.Admins = await _context.OrganizationToAdmins.Where(x => x.OrganizationId == id)
                .Select(x => x.ApplicationUser)
                .Where(x => x.Id != User.FindFirst(ClaimTypes.NameIdentifier).Value)
                .Select(x => x.Email)
                .ToListAsync();

            model.Signatories = await _context.OrganizationToSignatories.Where(x => x.OrganizationId == id)
                .Select(x => x.ApplicationUser)
                .Where(x => x.Id != User.FindFirst(ClaimTypes.NameIdentifier).Value)
                .Select(x => x.Email)
                .ToListAsync();

            model.Responsibles = await _context.OrganizationToResponsibles.Where(x => x.OrganizationId == id)
                .Select(x => x.ApplicationUser)
                .Where(x => x.Id != User.FindFirst(ClaimTypes.NameIdentifier).Value)
                .Select(x => x.Email)
                .ToListAsync();

            model.Managers = await _context.OrganizationToManagers.Where(x => x.OrganizationId == id)
                .Select(x => x.ApplicationUser)
                .Where(x => x.Id != User.FindFirst(ClaimTypes.NameIdentifier).Value)
                .Select(x => x.Email)
                .ToListAsync();

            return View(model);
        }

        public ActionResult AddAdmin(Guid id)
        {
            var model = new AddAdminViewModel
            {
                OrganizationId = id
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddAdmin(AddAdminViewModel model)
        {
            if (ModelState.IsValid)
            {

             

             

                var user =
                   await
                       _context.Users.FirstOrDefaultAsync(
                           x => x.NormalizedEmail.Equals(model.Email, StringComparison.OrdinalIgnoreCase));

                if (user == null)
                {
                    return View("AddWaitingUser", new WaitingUserView()
                    {
                        FromUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                        InviteEmail = model.Email,
                        OrganizationId = model.OrganizationId,
                        Position = (int)OrganizationPosition.Admin,
                        BackUrl = HttpContext.Request.Path.Value

                    });
                }
                else
                {
                    _context.OrganizationToAdmins.Add(new OrganizationToAdmin
                    {
                        OrganizationId = model.OrganizationId,
                        ApplicationUserId = user.Id
                    });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = model.OrganizationId });
            }
            return View(model);
        }

        public ActionResult AddManager(Guid id)
        {
            var model = new AddAdminViewModel
            {
                OrganizationId = id
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddManager(AddAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user =
                  await
                      _context.Users.FirstOrDefaultAsync(
                          x => x.NormalizedEmail.Equals(model.Email, StringComparison.OrdinalIgnoreCase));

                if (user == null)
                {
                    return View("AddWaitingUser", new WaitingUserView()
                    {
                        FromUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                        InviteEmail = model.Email,
                        OrganizationId = model.OrganizationId,
                        Position = (int)OrganizationPosition.Manager,
                        BackUrl = HttpContext.Request.Path.Value

                    });
                }
                else
                {
                    _context.OrganizationToManagers.Add(new OrganizationToManager
                    {
                        OrganizationId = model.OrganizationId,
                        ApplicationUserId = user.Id
                    });
                }

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = model.OrganizationId });
            }
            return View(model);
        }

        public ActionResult AddSignatory(Guid id)
        {
            var model = new AddAdminViewModel
            {
                OrganizationId = id
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddSignatory(AddAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user =
                  await
                      _context.Users.FirstOrDefaultAsync(
                          x => x.NormalizedEmail.Equals(model.Email, StringComparison.OrdinalIgnoreCase));
                

                if (user == null)
                {
                    return View("AddWaitingUser", new WaitingUserView()
                    {
                        FromUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                        InviteEmail = model.Email,
                        OrganizationId = model.OrganizationId,
                        Position = (int) OrganizationPosition.Signatory,
                        BackUrl = HttpContext.Request.Path.Value

                    });
                }
                else
                {
                    _context.OrganizationToSignatories.Add(new OrganizationToSignatory
                    {
                        OrganizationId = model.OrganizationId,
                        ApplicationUserId = user.Id
                    });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = model.OrganizationId });
            }
            return View(model);
        }

        public ActionResult AddResponsible(Guid id)
        {
            var model = new AddAdminViewModel
            {
                OrganizationId = id
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddResponsible(AddAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user =
                   await
                       _context.Users.FirstOrDefaultAsync(
                           x => x.NormalizedEmail.Equals(model.Email, StringComparison.OrdinalIgnoreCase));

                if (user == null)
                {  
                    return View("AddWaitingUser", new WaitingUserView()
                    {
                        FromUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                        InviteEmail = model.Email,
                        OrganizationId = model.OrganizationId,
                        Position = (int)OrganizationPosition.Responsible,
                        BackUrl = HttpContext.Request.Path.Value,
                    });
                }
                else
                {
                    _context.OrganizationToResponsibles.Add(new OrganizationToResponsible
                    {
                        OrganizationId = model.OrganizationId,
                        ApplicationUserId = user.Id
                    });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { id = model.OrganizationId });
            }
            return View(model);
        }

        public ActionResult DeleteAdmin(Guid id, string email)
        {
            var model = new AddAdminViewModel
            {
                OrganizationId = id,
                Email = email
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAdmin(AddAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var normalizedEmail = model.Email.ToUpper();
                var user = await _context.Users.FirstOrDefaultAsync(x => x.NormalizedEmail == normalizedEmail);
                var row = await _context.OrganizationToAdmins
                    .Where(x => x.ApplicationUserId == user.Id && x.OrganizationId == model.OrganizationId)

WebApp/Controllers/OrganizationSummaryController.cs
using System.Linq;
using System.Threading.Tasks;
using WebApp.Models;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    public class OrganizationSummaryController : Controller
    {
        private ApplicationDbContext _context;

        public OrganizationSummaryController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: OrganizationSummary
        public async Task<IActionResult> Index(Guid? id)
        {
            var model = await _context.Organizations
                .FirstOrDefaultAsync(x=>x.OrganizationId == id);
            return View(model);
        }

        
    }
}

WebApp/Views/Organizations/Create.cshtml
@model WebApp.Models.Organization

@{
    ViewData["Title"] = "Create";
}

<h2>Создать</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Организацию</h4>
        <hr />

        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Вернуться</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

WebApp/Views/Organizations/Delete.cshtml
@model WebApp.Models.Organization

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

WebApp/Views/Organizations/Details.cshtml
@model WebApp.Models.Organization

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Organization</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.OrganizationId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

WebApp/Views/Organizations/Edit.cshtml
@model WebApp.Models.Organization

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Organization</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <input type="hidden" asp-for="OrganizationId" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="OrganizationProfileId" class="control-label col-md-2">OrganizationProfileId</label>
            <div class="col-md-10">
                <select asp-for="OrganizationProfileId" class="form-control" />
                <span asp-validation-for="OrganizationProfileId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

WebApp/Views/Organizations/GetList.cshtml
@model IEnumerable<WebApp.Models.Organization>

@{
    ViewData["Title"] = "GetOrganizations";
}
<div class="row">
    <h2>Список организаций</h2>

    <div class="col-md-8">
        @if (Model.Any())
        {
            <table class="table table-bordered table-hover table-condensed table-striped">
                <thead>
                <tr>
                    <th>
                        Название
                    </th>
                    <th>
                    </th>
                    <th>
                    </th>
                </tr>
                </thead>
                <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.OrganizationId">изменить</a>
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.OrganizationId">удалить</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>


        }
        else
        {
            <h4>Список пуст</h4>
        }

    </div>
</div>

<input id="text" type="hidden" value="@ViewBag.Foo"/>



<div>
    <button id="down">скачать</button>
</div>
@section scripts{

    <script src="~/js/docxjs.js"></script>
    <script src="~/js/file-saver.js"></script>
    <script src="~/js/jszip-utils.js"></script>
    <script>


        $(document).ready(function () {
            $("#down").click(function() {
                var jsonData = $.parseJSON($('#text').val());
                WriteDocFile("/static/template.docx", jsonData);
            });
        });

        function WriteDocFile(file,data) {
            var loadFile = function(url, callback) {
                JSZipUtils.getBinaryContent(url, callback);
            }
            loadFile(file, function (err, content) {
                var doc = new Docxgen(content);
                doc.setData(data);
                doc.render();
                var output = doc.getZip().generate({ type: "blob" }); //Output the document using Data-URI
                saveAs(output, "output.docx");
            });
        }

    </script>

}

WebApp/Views/Organizations/Index.cshtml
@model WebApp.ViewModels.Organizations.IndexViewModel
@{
    ViewData["Title"] = "Index";
}

<h2>Организации</h2>

<p>
  <a class="btn btn-default" asp-action="Create">Создать организацию</a>
</p>

@if (Model.AsAdmin.Count > 0)
{

    <h3>Полный доступ как администратор к следующим организациям:</h3>

    <table class="table table-bordered table-hover table-condensed table-striped">
      <tr>
        <th>Название</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      @foreach (var item in Model.AsAdmin)
      {
          <tr>
            <td>@item.Name</td>
            <td>
              <a asp-controller="OrganizationAccess" asp-action="Index" asp-route-id="@item.OrganizationId">Управлять доступом</a>
            </td>
            <td>
              <a asp-action="Delete" asp-route-id="@item.OrganizationId">Удалить</a>
            </td>
            <td>
              <a asp-controller="OrganizationSummary" asp-action="Index" asp-route-id="@item.OrganizationId">Карточка</a>
            </td>
          </tr>
      }
    </table>
}

@if (Model.AsManager.Count > 0)
{
    <h3>Доступ как контрактный управляющий:</h3>

    <table class="table table-bordered table-hover table-condensed table-striped">
      <tr>
        <th>Название</th>
        <th></th>

      </tr>

      @foreach (var item in Model.AsManager)
      {
          <tr>
            <td>@item.Name</td>
            <td>
              <a asp-controller="OrganizationSummary" asp-action="Index" asp-route-id="@item.OrganizationId">Карточка</a>
            </td>
          </tr>
      }
    </table>
}

@if (Model.AsSignatory.Count > 0)
{
    <h3>Доступ как ответственный за подписание:</h3>

    <table class="table table-bordered table-hover table-condensed table-striped">
      <tr>
        <th>Название</th>
        <th></th>

      </tr>

      @foreach (var item in Model.AsSignatory)
      {
          <tr>
            <td>@item.Name</td>
            <td><a>Карточка</a></td>
          </tr>
      }
    </table>
}

@if (Model.AsResponsible.Count > 0)
{
    <h3>Доступ как ответственное должностное лицо:</h3>

    <table class="table table-bordered table-hover table-condensed table-striped">
      <tr>
          <th>Название</th>
          <th>email</th>
        <th></th>

      </tr>

      @foreach (var item in Model.AsResponsible)
      {
          <tr>
              <td>@item.Name</td>
              <td>@item.OrganizationProfile.Email</td>
            <td><a>Карточка</a></td>
          </tr>
      }
    </table>
}