WebApp/Controllers/AuctionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AutoMapper;
using Google.Apis.Calendar.v3;
using Google.Apis.Calendar.v3.Data;
using Google.Apis.Services;
using Google.Apis.Auth.OAuth2;
using Google.Apis.Auth.OAuth2.Flows;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.Code;
using WebApp.Models;
using WebApp.Services;
using WebApp.ViewModels.Auction;
using WebApp.ViewModels.Notification;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    [Authorize]
    public class AuctionController : Controller
    {
        #region constructor

        private readonly ApplicationDbContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IGoogleCalendar _calendar;

        public AuctionController(ApplicationDbContext context, SignInManager<ApplicationUser> signInManager, IGoogleCalendar calendar)
        {
            _context = context;
            _signInManager = signInManager;
            _calendar = calendar;
        }
        #endregion constructor

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewBag.Id = Guid.NewGuid();
            var auctions =
                await _context.AuctionProfiles.Include(x => x.Organization).AsNoTracking().OrderByDescending(x => x.AuctionDateStart).ToListAsync();

            var auctionView = Mapper.Map<IEnumerable<AuctionProfile>, IEnumerable<AuctionView>>(auctions);
            return View(auctionView);
        }

        #region actionProfile

        [HttpGet]
        public async Task<IActionResult> EditProfile(Guid? id)
        {
            if (id.HasValue && id.Value != Guid.Empty)
            {
                var auctionView = new AuctionView { AuctionProfileId = id.Value };
                var auctionProfile = await _context.AuctionProfiles.SingleOrDefaultAsync(x => x.AuctionProfileId.Eq(id.Value));
                if (auctionProfile != null)
                {
                    auctionView = Mapper.Map<AuctionProfile, AuctionView>(auctionProfile);
                }

                var auctionOrganizationId = auctionView.OrganizationId ?? Guid.Empty;

                var userid = User.FindFirst(ClaimTypes.NameIdentifier).Value; 

                auctionView.Organizations = _context.Organizations.AsNoTracking()
                    .Where(x =>
                    x.OrganizationToManagers.Any(y => y.ApplicationUserId.Equals(userid, StringComparison.OrdinalIgnoreCase))
                    || x.Responsibles.Any(y => y.ApplicationUserId.Equals(userid, StringComparison.OrdinalIgnoreCase))
                    || x.Signatories.Any(y => y.ApplicationUserId.Equals(userid, StringComparison.OrdinalIgnoreCase))
                    || x.Holders.Any(y => y.ApplicationUserId.Equals(userid, StringComparison.OrdinalIgnoreCase)))
                    .ToList()
                        .Select(x => new SelectListItem
                        {
                            Value = x.OrganizationId.ToString(),
                            Text = x.Name,
                            Selected = x.OrganizationId.Eq(auctionOrganizationId)
                        }).ToList(); ;

                return View(auctionView);
            }
            return NotFound("404");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditProfile(AuctionView auctionView)
        {
            if (ModelState.IsValid)
            {
                var auctionProfile = Mapper.Map<AuctionView, AuctionProfile>(auctionView);

                var auctionProfileExist = _context.AuctionProfiles
                    .Any(x => x.AuctionProfileId.Eq(auctionProfile.AuctionProfileId));

                if (auctionProfileExist)
                {
                    _context.AuctionProfiles.Update(auctionProfile);
                }
                else
                {
                    _context.AuctionProfiles.Add(auctionProfile);
                }
                _context.SaveChanges();

                //если с датами в порядке, вызываем календарь
                if (auctionProfile.AuctionDateStart.HasValue &&
                    auctionProfile.AuctionDateEnd.HasValue)
                {
                  await    _calendar.AddOrUpdate(auctionProfile);
                    
                }
               
            }

            ViewBag.error = ModelState.GetErrors();
            return RedirectToAction("EditProfile", new { Id = auctionView.AuctionProfileId });
        }

        public async Task<IActionResult> DeleteProfile(Guid id)
        {
            var auctionProfileDto =
                await _context.AuctionProfiles.AsNoTracking().SingleOrDefaultAsync(x => x.AuctionProfileId.Eq(id));

            var redirectUrl = Request.Headers["Referer"];
            if (auctionProfileDto != null)
            {
                await _calendar.Remove(auctionProfileDto);

                _context.Remove(auctionProfileDto);
                await _context.SaveChangesAsync();
            }

            if (!String.IsNullOrWhiteSpace(redirectUrl)) return Redirect(redirectUrl);
            else
                return RedirectToAction("GetMyList");
        }

        #endregion actionProfile

        #region purchaseProfile

        [HttpGet]
        public IActionResult EditPurchaseProfile(Guid? id)
        {
            if (id.HasValue && id.Value != Guid.Empty)
            {
                var ap = _context.PurchaseProfiles.
                    SingleOrDefault(x => x.AuctionProfileId.Eq(id.Value)) ??
                    new PurchaseProfile();

                ap.AuctionProfileId = id.Value;
                return View(ap);
            }
            return NotFound("404");
        }

        [HttpPost]
        public async Task<IActionResult> EditPurchaseProfile(PurchaseProfile data)
        {
            if (ModelState.IsValid)
            {
                var ap = _context.AuctionProfiles.SingleOrDefault(
                            x => x.AuctionProfileId.Eq(data.AuctionProfileId));
                if (ap == null)
                {
                    ap = new AuctionProfile { AuctionProfileId = data.AuctionProfileId };
                    _context.AuctionProfiles.Add(ap);
                }
                else
                {
                    _context.AuctionProfiles.Update(ap);
                }

                if (data.PurchaseProfileId.Eq(Guid.Empty))
                {
                    ap.PurchaseProfile = new PurchaseProfile();
                    data.PurchaseProfileId = Guid.NewGuid();
                    ap.PurchaseProfile = data;
                }
                else
                {
                    _context.PurchaseProfiles.Update(data);
                }
                await _context.SaveChangesAsync();
            }
            ViewData["Error"] = ModelState.GetErrors();

            return View(data);
        }

        #endregion purchaseProfile

        /// <summary>
        /// получить извещение
        /// id= auctionprofile
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> GetNoticeDocument(Guid id)
        {
            var errors = new List<string>();

            var ap = await _context.AuctionProfiles.AsNoTracking().SingleOrDefaultAsync(x => x.AuctionProfileId == id);

            var test = ap != null && ap.OrganizationId.HasValue;

            if (!test)
            {
                errors.Add("такого аукциона не сущесвует, либо вы не указали организацию");

            }
            else
            {
                var organization =
                    await
                        _context.Organizations.AsNoTracking()
                            .SingleOrDefaultAsync(x => x.OrganizationId.Eq(ap.OrganizationId.Value));
                if (organization == null)
                {
                    test = false;
                    errors.Add("указанная организация не существует");
                }

                var organizationProfile =
                    await
                        _context.OrganizationProfiles.AsNoTracking()
                            .SingleOrDefaultAsync(x => x.OrganizationProfileId.Eq(organization.OrganizationId));
                if (organizationProfile == null)
                {
                    test = false;
                    errors.Add("указанный профиль организации не существует");
                }
                var purchaseProfile =
                    await
                        _context.PurchaseProfiles.AsNoTracking()
                            .SingleOrDefaultAsync(x => x.AuctionProfileId.Eq(id));
                if (purchaseProfile == null)
                {
                    test = false;
                    errors.Add("указанный профиль закупок не существует");
                }

                var stock =
                    await
                        _context.Stocks.AsNoTracking()
                            .SingleOrDefaultAsync(x => x.StockId.Eq(organization.OrganizationId));
                if (stock == null)
                {
                    test = false;
                    errors.Add("указанный в организации склад не существует");
                }

                if (test)
                {

                    var doc = new AuctionNotificationViewModelStr
                    {
                        CustomerName = Helper.Safe(organizationProfile.RegistredName),
                        CustomerAddres =
                            Helper.Safe(
                                $"{organizationProfile.Street} {organizationProfile.Apartment} {organizationProfile.Office}"),

WebApp/Views/Shared/_Layout.cshtml
@using System
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Шаблонатор - @ViewData["Title"]</title>
    <meta name="description" content="">
    <link rel="icon" href="../../favicon.ico">

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/css/datatables.css" rel="stylesheet" />
        <link href="~/css/datepicker.css" rel="stylesheet" />
        <link href="~/css/responsive.dataTables.css" rel="stylesheet" />
    </environment>

    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="~/lib/html5shiv/dist/html5shiv.min.js"></script>
      <script src="~/lib/respondJs/dest/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    @*<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">*@
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Organizations" asp-action="Index" class="navbar-brand">Шаблонатор</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-controller="Organizations" asp-action="Index">Организации</a></li>

                        <li><a asp-controller="Auction" asp-action="GetMyList">Мои документы</a></li>

                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                Администрирование <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a asp-controller="Admin" asp-action="UserList">Список пользователей</a></li>
                                <li><a asp-controller="Organizations" asp-action="GetList">Список организаций</a></li>
                            </ul>
                        </li>
                    }
                </ul>

                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @RenderBody()
                <hr />
                <footer>
                    <p>&copy; @DateTime.Now.Year</p>
                </footer>
            </div>
        </div>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/js/moment.js"></script>
        <script src="~/js/moment_ru.js"></script>
        <script src="~/js/bootstrap-datetime.js"></script>
        <script src="~/js/jquery.dataTables.js"></script>
        <script src="~/js/dataTables.bootstrap.js"></script>
        <script src="~/js/dataTables.responsive.js"></script>
        <script src="~/js/docxjs.js"></script>
        <script src="~/js/file-saver.js"></script>
        <script src="~/js/jszip-utils.js"></script>
        <script src="~/js/main.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
        
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

    <script type="text/javascript">

        $(document).ready(function () {
            $('.datetime').datetimepicker({
                locale: 'ru'
            });
            $('.onlydate').datetimepicker({
                locale: 'ru',
                format: 'dd-MM-yyyy'

            });
            $('.onlytime').datetimepicker({
                locale: 'ru',
                format: 'LT'
            });
        });
    </script>

@await Html.PartialAsync("_ValidationScriptsPartial")
    @RenderSection("scripts", required: false)
</body>
</html>